### ISSUE TITLE
No way to check if sink is empty

### ISSUE THREAD

**Issue by Xaeroxe** [tomaka/rodio#104]
While designing my game engine I needed to know when a Sink had finished playing its sounds without requiring a new thread always borrowing my Sink to do so.  I created a custom version of rodio in my own repository that implements this feature, I'm willing to submit a PR for this if that's something you want in your API.

**Comment by Xaeroxe** [comment]
@tomaka This can all be done client side now so a custom version of rodio to accomplish this isn't really necessary but nonetheless it might be a useful feature to have in rodio itself.  I'd be content with closing this issue at this point but if you want a PR to add this I'd also be happy to make it.

**Comment by tomaka** [comment]
Sorry I skipped this issue.
That would be a good addition. If you want to make a PR, go ahead! But don't feel obligated to.

**Comment by Xaeroxe** [comment]
Fixed in #133
