### ISSUE TITLE
Sharing playback state

### ISSUE THREAD

**Issue by emoon** [tomaka/rodio#137]
Hi,

First thanks for a great create.

I have one question: I would like the rest of the application to be able to get a ref/copy of the current buffer of data that is being played. What I want to do is for example doing a oscilloscope or something like that.

I looked at how the FLAC decoder works and it decodes a block of data and then it has a index into that block. I likely want to do something similar in a custom `Source` but I also want to share it with other parts of the application.

Any suggestions on what the best approach for this would be?

Cheers!

**Comment by tomaka** [comment]
You probably want to implement `Source` yourself.

Writing a basic implementation of `Source` that can be shared is very simple, as you can just use an `Arc<Mutex<Vec<u8>>>`.
However in practice you probably want to avoid the cost of locking repeatedly the mutex by using a more complex system, for example by putting a distinction between the sender and receiver and making them communicate with a channel.

**Comment by emoon** [comment]
Yeah that makes sense and I agree that using a mutex here is likely the easiest but I don't think I want be locking as you say.

I didn't think about that I could just use regular channels here which should fit the bill nice.

Thanks!
