### ISSUE TITLE
Certain ogg files don't play correctly but don't appear obviously corrupt.

### ISSUE THREAD

**Issue by icefoxen** [tomaka/rodio#147]
ggez decodes a particular ogg or two incorrectly, giving corrupt output. Using release mode and debug mode both have the same results, so it's not my first thought, stuttering due to being too slow to keep the audio buffer full. vlc and audacious play the file perfectly fine. Re-encoding it with sox makes a file that ggez plays fine, but gives no decoding errors in the process. ogginfo shows similar info for both files, also gives no errors.

Repository that has a program that reproduces this, with included audio files: https://github.com/ggez/ggez-soundtest

Full report, with reproduction, here: https://github.com/ggez/ggez/issues/207

I'm stumped, so I'm kicking this upstream.

To do: make a reproduction that only uses rodio, not ggez.

**Comment by est31** [comment]
* audio_simple_with_error.ogg has an error
* audio_simple_with_error2.ogg plays fine
* Final_Fantasy_5_Cursed_Pirates_of_the_Sea_OC_ReMix.ogg plays fine as well

This is a lewton bug. I can reproduce this with lewton only. I'm investigating...

**Comment by est31** [comment]
This should be fixed by the new lewton release `0.9.2`, more specifically [this](1073e58b1c36bf77993dbd08433c4a4b61acd760) commit. Please test but I think this issue can be closed. You might need to perform the 0.8 upgrade for rodio, as earlier rodio doesn't depend on the 0.9 branch of lewton.
