### ISSUE TITLE
No sound in SamplesBuffer

### ISSUE THREAD

**Issue by alanpoon** [tomaka/rodio#151]
I wrote bytes into vector array, and inserted into the SamplesBuffer. It complies but there is no sound. Basically, I am trying to load sound from bytes, I could only find SamplesBuffer. Here is the code: https://gist.github.com/anonymous/b92600c200de921ed5cf393aff8daf68

**Comment by tomaka** [comment]
Not a direct solution to your problem, but you can take a look at the `music_ogg` example for how to read an OGG file.

**Comment by alanpoon** [comment]
I am working on android app. I am using android_glue::load_asset method to load the audio file which returns Result<Vec<u8>,Err>. I opened an issue in rust-sdl2's mixer load chunk from bytes array too. https://github.com/Rust-SDL2/rust-sdl2/issues/743. Any solution to load audio in android_glue?

**Comment by tomaka** [comment]
Aha! Your problem is that cpal (the library that rodio uses) is currently not working on Android at all.
