### ISSUE TITLE
Please release a 0.5.3 with recent commits

### ISSUE THREAD

**Issue by martinlindhe** [tomaka/rodio#153]
In https://github.com/tomaka/rodio/commit/8eaba65b5df8c0a44949070e59621365d5b248a5
default_endpoint() was exported, and usage examples recommend this pattern in the examples as seen by a potential user.
But this is not yet released, making user (me) confused.

With rodio 0.5.2:

```
warning: use of deprecated item 'rodio::get_default_endpoint'
  --> src\main.rs:10:20
   |
10 |     let endpoint = rodio::get_default_endpoint().unwrap();
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
``` 

changing:

```
error[E0425]: cannot find function `default_endpoint` in module `rodio`
  --> src\main.rs:10:27
   |
10 |     let endpoint = rodio::default_endpoint().unwrap();
   |                           ^^^^^^^^^^^^^^^^ did you mean `get_default_endpoint`?
```

**Comment by tomaka** [comment]
Hmm, I'm pretty sure that this is supposed to work.

**Comment by martinlindhe** [comment]
It works if i point to the git repo in my Cargo.toml dependency, but not if i depend on the 0.5.2 version released in august, but it wasn't until october that `default_endpoint` was made public, in https://github.com/tomaka/rodio/commit/8eaba65b5df8c0a44949070e59621365d5b248a5#diff-b4aea3e418ccdb71239b96952d9cddb6R95

**Comment by tomaka** [comment]
Oh I see.
