### ISSUE TITLE
Latest release breaks semver

### ISSUE THREAD

**Issue by Xaeroxe** [tomaka/rodio#155]
Version 0.5.3 upgraded cpal to 0.6.  This breaks semver since the cpal `EndpointsIterator` structure is exposed in the rodio API.

**Comment by Xaeroxe** [comment]
Relevant line in our broken build: https://ci.appveyor.com/project/amethyst/amethyst/build/1.0.1535/job/o2l58flb23w5krgo#L511

**Comment by Xaeroxe** [comment]
@tomaka Amethyst considers this a high priority, if this and winit 0.10.1 aren't yanked we'll need to release an emergency patch to get our crates building again.

**Comment by Xaeroxe** [comment]
Our latest version on crates wasn't using winit 0.10 fortunately so we only needed to lock down our rodio version to fix it.  We've released `amethyst_audio` 0.1.1 to get things building again.

**Comment by tomaka** [comment]
Err... Yanked and re-released. Sorry for the trouble.
