### ISSUE TITLE
Update hound dependency to 3.3.1

### ISSUE THREAD

**Issue by cormac-obrien** [tomaka/rodio#157]
The current version of hound used by rodio (`1.0.0`) fails when reading certain valid WAV files (see ruuda/hound#20). All the tests still pass with the dependency in `Cargo.toml` updated to `3.3.1`. Is there anything preventing rodio's version of hound from being updated?

**Comment by tomaka** [comment]
Nothing's preventing the update I guess. Could you submit a pull request for it?
