### ISSUE TITLE
How to use Pausable and Stoppable?

### ISSUE THREAD

**Issue by mathstuf** [tomaka/rodio#181]
The structures must be moved to a `Sink` before they can be used, but then the `pause()` and `stop()` methods can't be called anymore. I see that there are comments to add examples for how to use them. Am I missing something?

**Comment by tomaka** [comment]
Here is an example: https://github.com/tomaka/rodio/blob/8bf1bf58517b70cbdf9cd8d9ee8ed1588157da29/src/sink.rs#L65-L78

**Comment by mathstuf** [comment]
Ah, `perodic_access` is what I was missing. Thanks.
