### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by est31** [tomaka/rodio#185]
Hi, it'd be great to get a new version released. I have a lewton update upcoming but it will be on the 0.9 branch and only unreleased rodio uses it. Thanks!

**Comment by tomaka** [comment]
Could you open a PR that bumps the version in Cargo.toml and update the CHANGELOG?
There's an auto-publish system that will publish it once merged.

**Comment by est31** [comment]
@tomaka sure, I've filed #186.
