### ISSUE TITLE
error: failed to run custom build command for `alsa-sys v0.1.2`      

### ISSUE THREAD

**Issue by GopherJ** [tomaka/rodio#200]
There is an error when it compiles `alsa-sys`

**Comment by GopherJ** [comment]
@thiolliere Hello, thanks for your reply. I still got this error: 

```
process didn't exit successfully: `/home/cheng/Project/Rust/rodio/examples/mp3/target/debug/build/alsa-sys-89668916c5ee996e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by GopherJ** [comment]
I failed to find `alsa.pc`, it's strange...before that I've installed `libalsaplayer-dev`.

**Comment by thiolliere** [comment]
yes indeed I just find out on debian alsa dev files seems to be in package libasound2-dev instead

**Comment by GopherJ** [comment]
Thank you very much! It works well after installed `libasound2-dev`!

**Comment by blemelin** [comment]
Had the same problem. This should probably be documented in the `README.md`.

Something like this :

```markdown
## Dependencies
This crate requires `libasound2-dev` on Debian and derivatives (Ubuntu, Pop OS, ...).
```

**Comment by vmontes** [comment]
> In Void Linux, install the following `alsa-lib` `alsa-firmware` `alsa-lib-devel` I am not quite sure which one exactly solved my problem, but it was solved anyway

Thanks, this worked for my Fedora (using dnf)

**Comment by GyulyVGC** [comment]
> In Void Linux, install the following `alsa-lib` `alsa-firmware` `alsa-lib-devel` I am not quite sure which one exactly solved my problem, but it was solved anyway

It should be the last one

**Comment by Resonanz** [comment]
Needed this on Ubuntu 24:

https://askubuntu.com/questions/1396181/package-alsa-was-not-found-in-the-pkg-config-search-path-perhaps-you-should-add

**Comment by dvdsk** [comment]
Just added a note on the readme. Would that have helped you out @Resonanz ?

**Comment by Resonanz** [comment]
Thanks. That would have helped. Picky much... needs a space: "Dependencies(Linux only)" :-)
