### ISSUE TITLE
Cannot use one source multiple times

### ISSUE THREAD

**Issue by Codadillo** [tomaka/rodio#211]
Whenever you call `sink.append`, `play_once`, or `play_raw`, the source you pass in is consumed.

This code:
```rust
let device = rodio::default_output_device().unwrap();
let source = File::open(PATH).unwrap();
rodio::play_once(&device, source);
rodio::play_once(&device, source);
```
Gives the error:
```
error[E0382]: use of moved value: `source`
  --> src/main.rs:18:31
   |
17 |     rodio::play_once(&device, source);
   |                               ------ value moved here
18 |     rodio::play_once(&device, source);
   |                               ^^^^^^ value used here after move
   |
   = note: move occurs because `source` has type `std::fs::File`, which does not implement the `Copy` trait
```

Trying to pass in a borrow (`&source` instead of `source`), results in this error:
```
error[E0597]: `source` does not live long enough
  --> src/main.rs:17:32
   |
17 |     rodio::play_once(&device, &source);
   |                                ^^^^^^ borrowed value does not live long enough
...
20 | }
   | - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...
```

Is this intentional? If so, is the best solution just to reread from the sound file and make a new source?

**Comment by SongWithoutWords** [comment]
I feel like this should be reopened - I am very confused by this library for this reason.

**Comment by tomaka** [comment]
A `File` is essentially a stream. If you want to play the same sound twice in parallel, you need two streams. The only other way you can technically do in a different way would be to buffer the content of the file in memory, which can be done with `buffered()`. But I of course wouldn't recommend that.
So yes, open the file twice.

**Comment by tomaka** [comment]
If it's a sound effect, then you may want to buffer it using `buffered()` or a similar method.
