### ISSUE TITLE
MP3 playback clipping.

### ISSUE THREAD

**Issue by GlenCFL** [tomaka/rodio#212]
MP3 playback using the [mp3 music example](https://github.com/tomaka/rodio/blob/master/examples/music_mp3.rs) seems to be clipping something like a second of audio from the end of the audio stream. This is particularly apparent on short audio clips, with a 1 second duration MP3 not outputting any sound and a 2 second duration MP3 cutting out midway through playback.

This is on Windows 10 x64 using rodio 0.8.1.

**Comment by germangb** [comment]
Could you file an issue in the `minimp3-rs` crate? The following line might return an early EOF

https://github.com/germangb/minimp3-rs/blob/master/src/lib.rs#L78

**Comment by germangb** [comment]
Seems the `minimp3` crate is returning an early EOF. Could you file a bug in https://github.com/germangb/minimp3-rs/issues ?

Thanks!
