### ISSUE TITLE
Add a mp3 decoder

### ISSUE THREAD

**Issue by tomaka** [tomaka/rodio#36]

**Comment by icefoxen** [comment]
libmad seems like a small and reasonably nice C mp3 decoder; translating it might not be too huge of a task.

**Comment by tomaka** [comment]
@icefoxen I did so in https://github.com/tomaka/rodio/pull/48 but ended up not merging the PR because it is GPL2.

**Comment by icefoxen** [comment]
Looking at this again, liblame is LGPL 2...  but that appears to still be incompatible with the Apache Public License, per http://www.apache.org/legal/resolved.html#category-x

**Comment by lieff** [comment]
Here MIT and CC0 https://github.com/germangb/minimp3-rs

**Comment by barzamin** [comment]
I've [written a safe, Rusty wrapper](https://github.com/germangb/minimp3-rs/pull/1) around the raw `minimp3` bindings @lieff mentioned; once that's been merged, better tested, and published, it's trivial to integrate into Rodio (I've already done it on a fork).
