### ISSUE TITLE
Add sound spatialization

### ISSUE THREAD

**Issue by tomaka** [tomaka/rodio#40]

**Comment by tomaka** [comment]
Some quick reference here: https://webaudio.github.io/web-audio-api/#Spatialization

**Comment by Xaeroxe** [comment]
I'd like to take a crack at implementing this.  If I'm successful would you like a PR @tomaka ?

**Comment by tomaka** [comment]
@Xaeroxe Sure.

**Comment by Xaeroxe** [comment]
PR opened: https://github.com/tomaka/rodio/pull/125

**Comment by Xaeroxe** [comment]
PR merged.  I believe we can close this now.
