### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by cmr** [tomaka/rodio#64]
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback, and has protections from
patent trolls and an explicit contribution licensing clause. However, the
Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as
MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and
doing so would be wise for this project. This also makes this crate suitable
for inclusion in the Rust standard distribution and other project using dual
MIT/Apache.
# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright) and then add the following to
your README:

```
## License

Licensed under either of
 * Apache License, Version 2.0 ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)
at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, use the following boilerplate (based on that used in Rust):

```
// Copyright (c) 2015 t developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
```

And don't forget to update the `license` metadata in your `Cargo.toml`!
# Contributor checkoff
- [x] @tomaka

**Comment by Xaeroxe23** [comment]
- [x] @Xaeroxe23

**Comment by Xaeroxe23** [comment]
Contributor checkoff update:

- [ ] @icefoxen 
- [ ] @est31 
- [ ] @petrochenkov 
- [ ] @psych0d0g

**Comment by est31** [comment]
I license all my past, present, and future contributions to this crate, under the dual `MIT/Apache-2.0` license as above, without any additional terms or conditions.

**Comment by petrochenkov** [comment]
I agree with relicensing my contributions to https://github.com/tomaka/rodio to the dual MIT/Apache-2.0 license.

**Comment by icefoxen** [comment]
Totes mc'goats. :goat:

Um, I mean, I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by tomaka** [comment]
I checked myself off.

**Comment by Xaeroxe23** [comment]
https://github.com/tomaka/rodio/commit/9d3cadd7b5550440b85bc8a3ac52f640a6c3eb78 So this is @psych0d0g 's only commit to this project.  Does this qualify as copyright protected work?  I'm not sure what the criteria is on that.

**Comment by icefoxen** [comment]
Copyright (in the US) protects creative works of expression fixed in a permanent state.  Source: <http://www.newmediarights.org/business_models/artist/ii_what_can_and_can%E2%80%99t_be_copyrighted> (which was more informative than the US copyright office's page, unfortunately).  I doubt a version number bump realistically qualifies as this.  Being programmers, naturally we will ask "but then where is the line drawn?" and the answer to that is probably amazingly poorly-defined and nonsensical, as the Google vs. Oracle lawsuit over the Java API demonstrates.

**Comment by tomaka** [comment]
Yes I agree that it's not a problem.
I wanted to do the relicensing already, but I'm too lazy. If someone opens a PR I'll merge it.

**Comment by est31** [comment]
Update of the list:

- [ ] @psych0d0g
- [ ] @SiIky
- [ ] @cormac-obrien
- [ ] @camjackson
- [ ] @lennartS
- [ ] @thiolliere
- [ ] @barzamin
- [ ] @chyvonomys
- [ ] @frazar

**Comment by barzamin** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by frazar** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by chyvonomys** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by lennartS** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by thiolliere** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by camjackson** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by SiIky** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by cormac-obrien** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by est31** [comment]
Thanks everyone! The only missing mark is from @psych0d0g , but per comment above, it was decided that their contribution can be considered as trivial and therefore no consent by them is required.

I've filed #178 to finish the relicensing process. There is an archived copy of this issue [here](http://web.archive.org/web/20180827182532/https://github.com/tomaka/rodio/issues/64), for the case that accounts or posts are deleted. Thanks again.
