### ISSUE TITLE
Sound stops playing at seemingly random locations

### ISSUE THREAD

**Issue by nicokoch** [tomaka/rodio#67]
I'm on linux.
When I run the basic example, it never plays all the beeps. It just stops playback at random times (after ~100ms to ~4 seconds).
To confirm I loaded a .wav song from my music collection and tried to play it. Same results.

I do not understand low level sound playback very well, so any pointers on how I can give better debug information would be appreciated.

**Comment by tomaka** [comment]
If you want to help, knowing if one of these lines is reached would be useful:

https://github.com/tomaka/cpal/blob/master/src/alsa/mod.rs#L305
https://github.com/tomaka/cpal/blob/master/src/alsa/mod.rs#L265
https://github.com/tomaka/cpal/blob/master/src/alsa/mod.rs#L360

**Comment by nicokoch** [comment]
Yes, I downloaded cpal manually and added some output at those lines. Here's the result:
```
cargo run --example basic
     Running `target/debug/examples/basic`
Reached src/alsa/mod.rs - l.360
Reached src/alsa/mod.rs - l.360
Reached src/alsa/mod.rs - l.360
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
Reached src/alsa/mod.rs - l.305
...
```

It hangs at l.305 until I ctrl + c.

**Comment by tomaka** [comment]
But which one is triggered?

**Comment by nicokoch** [comment]
Line 305, as the output says ^.^

**Comment by tomaka** [comment]
I guess there are two problems here:

1) The samples are not submitted fast enough, which leads to an underrun.
2) An underrun is supposed to be recovered automatically, which is not the case here.

**Comment by nicokoch** [comment]
Anything I can do to help fix this?

**Comment by nicokoch** [comment]
Ok, I tingled around a bit and found a fix:

In https://github.com/tomaka/cpal/blob/master/src/alsa/mod.rs#L305 , replace `0` with `self.buffer_len`.

When we have an underflow, pending samples should be 0, but in the current code, `self.buffer_len` is returned, which is wrong imho.
