### ISSUE TITLE
Examples crash under Mac OS X

### ISSUE THREAD

**Issue by SirVer** [tomaka/rodio#94]
This is a pristine checkout on e8bb880c42df99a095e19a16912a77dd5e11fe0d (latest master). No other audio programs are running right now.

~~~
$ cargo run --release --example basic
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/examples/basic`
-> exit code 1

$ target/release/examples/basic
zsh: segmentation fault (core dumped)  target/release/examples/basic
~~~

This is a MacBookPro Retina 15 Inch, Early 2013 with Intel Core i7 running OS X El Capitan.

**Comment by tomaka** [comment]
Thanks for the report, but please open an issue for cpal instead: https://github.com/tomaka/cpal
Since rodio doesn't contain any unsafe code, it can't be the cause.

**Comment by SirVer** [comment]
Done: https://github.com/tomaka/cpal/issues/148

CPAL does not crash though (see the bug report). But it also does not play a sound. Maybe CPALs interface does not fulfill the safety guarantees/is unsound?
